# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#permalink:        pretty
permalink:        date

timezone:  		  Asia/Shanghai
lsi:			  true

# Setup
title:            路边阳春面
tagline:          '每天不同的味道'
description:      '<a href="http://weibo.com/liuihc" target="_blank">路边阳春面</a><br/>每天不同的味道'
url:              http://weibo.com/liuihc
baseurl:          '/'
paginate:         1

author:
  name:           'BoLau'
  url:            http://weibo.com/liuihc

# Custom vars
version:          1.0.0

github:
  repo:           http://weibo.com/liuihc
