# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#permalink:        pretty
permalink:        date

include:     	  ['.htaccess']

timezone:  		  Asia/Shanghai
lsi:			  true

# Setup
title:            Know Nothing
tagline:          'You know nothing'
description:      '<a href="http://weibo.com/liuihc" target="_blank">You know nothing</a>
url:              http://weibo.com/liuihc
baseurl:          '/'
paginate:         1

author:
  name:           'BoLau'
  url:            http://weibo.com/liuihc

# Custom vars
version:          1.0.0

github:
  repo:           http://weibo.com/liuihc

pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
